### ISSUE TITLE
Could you upload the processed example dataset?

### ISSUE THREAD

**Issue by Sugar55888** [mbjurca/RT_GS2#1]
The download link for processed version of the Replica dataset seems to be inconsistent with the data directory provided in Readme. There are no files such as color_mapping_remaped.yaml, etc. Thank you!

**Comment by MihneaJurca-dotLumen** [comment]
Please check the `configs/dataset/Replica` as mentioned in the readme.

**Comment by mbjurca** [comment]
Please check the `configs/dataset/Replica` as mentioned in readme.

**Comment by Sugar55888** [comment]
@mbjurca Hi, I follow the instructions in readme to run the project. The previous steps are all normal, but when running python models/scripts/render_geom_features_replica.py, an error AttributeError: 'GaussianModel' object has no attribute 'get_features_geom' appears. It seems that you have modified the original gaussian_splatting, but this part does not seem to be uploaded to the repository. Could you give me some help? Thank you!

**Comment by mbjurca** [comment]
Yes, you are right; the Gaussian splatting code was modified. The modules were not properly pushed to the repo. Thank you for noticing, I will fix it ASAP.

**Comment by mbjurca** [comment]
@Sugar55888 the files of the models were pushed on the repo.

**Comment by Sugar55888** [comment]
@mbjurca I have successfully run the project after some adjustments to the dataloader. Thank you！

**Comment by Sugar55888** [comment]
@mbjurca Hi, I would also like to ask how you get the image semantic labels in ScanNet++ for evaluation? This dataset does not seem to provide image-level semantic labels. Is it by projecting the 3D semantic labels to 2D?

**Comment by mbjurca** [comment]
Yes indeed, the 2D labels have to be extracted from the 3D semantic reconstruction. I used [this](https://github.com/scannetpp/scannetpp/tree/rast_semantic?tab=readme-ov-file#rasterize-3d-semantics-onto-2d-images) branch in order to do it.

**Comment by Sugar55888** [comment]
@Thank you!

**Comment by Sugar55888** [comment]
@mbjurca Thank you!
